export type PostCardType = {
	postId: number;
	postTitle: string;
	postContext: string;
	posterId: number;
	posterName: string;
	profilePicture: string;
	upvotes: number;
	downvotes: number;
	commentsCount: number;
	favorites: number;
	tags: string[];
	createdAt: string;
};
export type QuestionCardType = {
	questionId: number;
	questionTitle: string;
	questionContext: string;
	questionerId: number;
	questionerName: string;
	profilePicture: string;
	upvotes: number;
	commentsCount: number;
	favorites: number;
	isSolved: boolean;
	tags: string[];
	createdAt: string;
};
export type sampleNotification = {
	userId: number;
	replierId: number;
	replierName: string;
	postTitle: string;
	questionTitle: null;
	isRead: boolean;
	createdAt: string;
	NotificationId: number;
	postId: number;
	questionId: null;
};
